#!/usr/bin/env python3
"""161: rebuild the thesis Table II (left-turn + cut-in merged) from the tables3 merged CSVs written by scripts/90.

Reproduces the hand-merged layout of Thesis/tables/tables3_leftturn_cutin_merged.tex: 4 groups x 3 methods, columns
DTW | D_int | Var ratio | Cov.@1000 | Corner cov.@1000 | Bg. collision | Off-road | Real (bg/off-road of the replay).
Every value and every bold mark comes from the CSV columns <col>_display / <col>_bold; the SAKURA routed share comes
from method_label ("SAKURA (93% routed)"); n = n_class. Nothing is typed by hand.
Usage:
  python -B exp_ours3_svd5/scripts/161_thesis_table2_tex.py                 # write results/final/tables3/..._thesis.tex
  python -B exp_ours3_svd5/scripts/161_thesis_table2_tex.py --compare FILE  # cell-by-cell diff against an existing tex
  python -B exp_ours3_svd5/scripts/161_thesis_table2_tex.py --install       # also copy into Thesis/tables/
"""
import argparse
import re
import shutil
from pathlib import Path

import pandas as pd

PROJECT = Path(__file__).resolve().parents[1]
ROOT = PROJECT.parent
T3 = PROJECT / "results/final/tables3"
OUT = T3 / "tables3_leftturn_cutin_merged_thesis.tex"
THESIS = ROOT / "Thesis/tables/tables3_leftturn_cutin_merged.tex"
GROUPS = [("tables3_leftturn_merged.csv", "keeptl", r"Agent-LT N$\to$E"),
          ("tables3_leftturn_merged.csv", "keeptl_sw", r"Agent-LT S$\to$W"),
          ("tables3_cutin_merged.csv", "cutinl", "Cut-in (left)"),
          ("tables3_cutin_merged.csv", "cutinr", "Cut-in (right)")]
METHODS = ["sakura_route", "svd_d5", "ours"]
COLS = ["sim_dtw", "sim_int", "var", "cov", "corner", "coll", "offroad"]


def method_tex(row):
    if row.method_key == "sakura_route":
        m = re.search(r"(\d+)%\s*routed", str(row.method_label))
        return r"SAKURA$^{" + (m.group(1) if m else "?") + r"\%\,\mathrm{routed}}$"
    return {"svd_d5": "SVD(d=5)", "ours": "Ours"}[row.method_key]


def cell(row, col):
    v = str(row[f"{col}_display"])
    bold = str(row[f"{col}_bold"]).strip().lower() == "true"
    return rf"\textbf{{{v}}}" if bold else v


def build():
    frames = {f: pd.read_csv(T3 / f, dtype=str) for f in {g[0] for g in GROUPS}}
    body = []
    for gi, (f, key, label) in enumerate(GROUPS):
        t = frames[f]
        g = t[t.group.eq(key)].set_index("method_key")
        real = g.loc["real"]
        n = int(float(g.loc["ours", "n_class"]))
        for mi, mk in enumerate(METHODS):
            r = g.loc[mk].copy()
            r["method_key"] = mk
            cells = " & ".join(cell(r, c) for c in COLS)
            if mi == 0:
                lead = rf"\multirow{{3}}{{*}}{{{label}}} & \multirow{{3}}{{*}}{{{n}}} & {method_tex(r)}"
                tail = rf" & \multirow{{3}}{{*}}{{{real['coll_display']}/{real['offroad_display']}}} \\"
            else:
                lead = f" &  & {method_tex(r)}"
                tail = r" & \\"
            body.append(f"{lead} & {cells}{tail}")
        if gi < len(GROUPS) - 1:
            body.append(r"\midrule")
    head = [
        r"% Combined left-turn and cut-in results; generated by exp_ours3_svd5/scripts/161_thesis_table2_tex.py from",
        r"% results/final/tables3/tables3_{leftturn,cutin}_merged.csv (values and bolding exactly as in the CSVs).",
        r"\begin{table*}[!t]", r"\centering", r"\footnotesize", r"\setlength{\tabcolsep}{4pt}",
        r"\caption{Comparison on left-turn and cut-in scenarios: trajectory reconstruction, sampling coverage, and replay validity.}",
        r"\label{tab:tables3-leftturn-cutin-merged}", r"\resizebox{\textwidth}{!}{%", r"\begin{tabular}{lllrrrrrrrr}", r"\toprule",
        r"\multicolumn{5}{c}{} & \multicolumn{5}{c}{Method + KDE Sampling} & \\", r"\cmidrule(lr){6-10}",
        r"Scenario & $n$ & Method & DTW~[m] $\downarrow$ & $D_{\mathrm{int}}$ $\downarrow$ & Var.\ ratio $\to$ 1 & Cov.@1000 $\uparrow$ & Corner cov.@1000 $\uparrow$ & Bg.\ collision $\downarrow$ & Off-road $\downarrow$ & Real$^\dagger$ \\",
        r"\midrule"]
    foot = [r"\bottomrule", r"\end{tabular}%", "}", r"\vspace{2pt}",
            r"\parbox{\textwidth}{\scriptsize $^\dagger$ Real replay reference: background collision/off-road.}", r"\end{table*}", ""]
    return "\n".join(head + body + foot)


def data_rows(text):
    """The 12 data rows, whitespace-normalised, for a cell-by-cell comparison."""
    rows = [ln for ln in text.splitlines() if ln.count("&") >= 9 and "Scenario" not in ln and "multicolumn{5}" not in ln]
    return [re.sub(r"\s+", " ", ln).strip() for ln in rows]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--compare", type=Path, default=None)
    ap.add_argument("--install", action="store_true")
    args = ap.parse_args()
    tex = build()
    OUT.write_text(tex)
    print(f"wrote {OUT}")
    if args.compare:
        a, b = data_rows(args.compare.read_text()), data_rows(tex)
        diffs = [(i, x, y) for i, (x, y) in enumerate(zip(a, b)) if x != y]
        print(f"compare vs {args.compare}: {len(a)} vs {len(b)} data rows, {len(diffs)} differing")
        for i, x, y in diffs:
            print(f"  row {i}:\n    old: {x}\n    new: {y}")
    if args.install:
        shutil.copyfile(OUT, THESIS)
        print(f"installed -> {THESIS}")


if __name__ == "__main__":
    main()
